name: Build release
description: Prepare the environment and build the host binary and the docs site

runs:
  using: composite
  steps:
    - uses: ./.github/actions/prepare
      with:
        cache: enabled
        prepare-for-build: enabled

    - name: Build
      shell: bash
      run: just build-release

    - name: Build the docs site
      shell: bash
      run: just docs-build
