[changelog]
header = """
# Changelog

"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
            {% if commit.breaking %}**Breaking:** {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = '^v[1-9][0-9]{3}\.(1[0-2]|[1-9])\.(0|[1-9][0-9]*)$'
use_branch_tags = true
sort_commits = "newest"
commit_parsers = [
    { message = '^chore\(release\)', skip = true },
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Fixes" },
    { message = "^perf", group = "<!-- 2 -->Performance" },
    { message = "^refactor", group = "<!-- 3 -->Refactoring" },
    { message = "^docs", group = "<!-- 4 -->Documentation" },
    { message = ".*", group = "<!-- 5 -->Maintenance" },
]
