name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: build:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/prepare
        with:
          cache: enabled
          prepare_for_build: enabled

      - name: Build
        run: cargo build -p nibrunnerd --release --target x86_64-unknown-linux-musl
