name: checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/prepare
        with:
          cache: disabled
          prepare_for_build: disabled

      - name: Check Rust Codestyle
        run: just fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/prepare
        with:
          cache: enabled
          prepare_for_build: disabled

      - name: Lint
        run: just lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/prepare
        with:
          cache: enabled
          prepare_for_build: disabled

      - name: Run Tests
        run: just test

  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/prepare
        with:
          cache: enabled
          prepare_for_build: disabled

      - name: Check the schemas are current
        run: just check-schema

  checks-passed:
    if: always()
    name: checks:required
    needs: [codestyle, lint, tests, schema]
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "Some jobs failed or were cancelled"
            exit 1
          fi
          echo "All CI jobs passed"
